import 'package:open_filex/open_filex.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';

/// Helper service for dossier actions (sharing, opening)
/// Backend-first architecture: PDF generation is now handled strictly by the Python backend.
class OfflineDossierService {
  
  /// Open the saved PDF using the device's native viewer.
  static Future<void> openPdf(String filePath) async {
    await OpenFilex.open(filePath);
  }

  /// Share the PDF via WhatsApp, email, or any other app.
  static Future<void> sharePdf(String filePath, String callId) async {
    await Share.shareXFiles(
      [XFile(filePath)],
      subject: 'PhaseGuard Forensic Evidence — $callId',
      text: 'Cyber crime evidence dossier generated by PhaseGuard.\n'
          'Report at: https://cybercrime.gov.in | Helpline: 1930',
    );
  }

  /// Open cybercrime.gov.in in the browser.
  static Future<void> openCybercrimePortal() async {
    final uri = Uri.parse('https://cybercrime.gov.in');
    if (await canLaunchUrl(uri)) {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    }
  }

  /// Call the national cybercrime helpline (1930).
  static Future<void> dialCybercrimeHelpline() async {
    final uri = Uri.parse('tel:1930');
    if (await canLaunchUrl(uri)) {
      await launchUrl(uri);
    }
  }
}
