import re

content = open('D:/PhaseGuard/apps/api/factcheck/local_llm.py', 'r', encoding='utf-8').read()

hindi_expansion = '''
            # EXTENDED HINDI KEYWORDS (500+ match English parity)
            "cbi warrant", "digital arrest", "police case", "fir darj ho chuki hai", "cbi officer bol raha hu",
            "customs mein parcel fasa hai", "illegal saman", "parcel block ho gaya", "fine pay karna hoga",
            "bijli kat jayegi aaj raat", "bill update nahi hua", "link pe click karke pay karo",
            "otp bata do varna", "kyc update nahi hai", "sim card band ho jayega", "aadhaar link nahi hai",
            "atm card block", "credit card limit", "personal details verify", "video call karo",
            "hospital mein accident", "urgent 50000 chahiye", "surgery ke liye paise bhejo", "mera phone kho gaya",
            "loan ki kisht baaki hai", "contact list walo ko bhej dunga", "private video leak kar dunga",
            "youtube video like karo", "part time job", "work from home", "google review job",
            "double ho jayenge paise", "guaranteed returns", "investment scheme", "lottery lag gayi hai",
            "tax evasion", "income tax department", "court se warrant aaya hai", "bail leni padegi",
            "police station aana padega", "kisi ko batana mat", "turant paise transfer karo", "rbi account",
            "insurance policy lapse", "processing fee lagegi", "refund aayega otp do", "customer care se bol raha hu",
            "screen share karo", "anydesk app download karo", "phone hack ho gaya hai", "virus nikal dunga",
            "shaadi dot com", "nri ladka", "gift customs", "flight miss", "airport pe fasa hu",
            "pension fas gayi hai", "pf ka paisa nikalna hai", "mseb bill", "account freeze ho gaya",
            "beta this is your mom", "hospital emergency surgery", "serious accident", "in jail for no reason",
            "papa accident", "mummy hospital", "bhai jail mein", "accident ho gaya", "hospital mein hoon",
            "paisa chahiye urgently", "48000 chahiye", "40000 chahiye", "25000 chahiye", "operation ke liye paisa",
            "emergency surgery chahiye", "using borrowed phone", "my phone is broken", "using friend phone",
            "kisi ko mat batana", "mat batana abhi", "secret rakhna", "sirf tumse bol raha hoon",
            "turant bhej do", "abhi bhej do paisa", "baad mein wapas kar dunga", "hospital se bol raha hoon",
            "video record kar liya", "video leak kar dunga", "video bhej dunga", "facebook friends ko bhej",
            "relatives ko bhej dunga", "youtube par upload", "compromising video", "personal video",
            "whatsapp video call record", "50000 nahi bheje", "nahi bheje toh", "share karo warna",
            "transfer karo warna", "instagram par daal", "workplace ko tag", "office mein bhej dunga",
            "morphed photo", "photo viral kar dunga", "screenshot bhej dunga", "intimate video",
            "private video leak", "nude video", "objectionable content", "contact list access",
            "contact list mein se", "contacts ko bhej dunga", "photos morph karke", "morphed photos contacts ko",
            "loan app se liye the", "due date aaj hai", "penalty ke sath pay", "recovery agent aayega",
            "aapki contact list hai mere paas", "saare contacts ko", "whatsapp forward kar dunga",
            "legal notice bhejenge", "court mein case", "arrest ho jayega loan ke liye", "loan recovery",
            "loan overdue", "emi bounce", "loan default", "bijli kategi", "bijli band ho jayegi",
            "light kat jayegi", "power cut ho jayega", "mseb", "bescom", "tata power", "adani electricity",
            "bijli vibhag", "meter reading update", "bill unpaid", "outstanding electricity bill",
            "disconnection notice", "link par pay karein electricity", "pay via link", "abhi online pay karo",
            "10 rupaye ka payment link", "1 rupaye pay karo verify karne", "tonight 9 baje kategi",
            "tonight power disconnected", "9:30 pm disconnection", "vip whatsapp group", "vip group join karo",
            "exclusive trading group", "200% returns guaranteed", "100% returns", "triple your money",
            "sebi registered advisor", "penny stock double", "insider tip", "demat account id password",
            "trade laga dunga", "humare group mein", "crypto investment platform", "high return scheme",
            "daily profit 5000", "weekly 20000 earn karo", "passive income", "trading bot", "ai trading software",
            "automated trading", "pm yojana file charge", "kisan samman nidhi otp", "pradhan mantri yojana",
            "government scheme registration fee", "aadhaar otp bataiye scheme ke liye", "muft bijli yojana",
            "free gas cylinder yojana", "ayushman bharat", "ration card update karo", "jan dhan account update",
            "covid relief fund disbursement", "pm kisan status update otp", "scholarship payment",
            "scholarship ke liye otp", "fedex customs", "customs clearance fee", "dhl parcel seized",
            "package seized at customs", "customs duty pending", "clear customs payment", "your parcel has illegal items",
            "parcel intercepted", "international shipment blocked", "clearance fee 85000", "customs department call",
            "pay to release package", "shaadi.com profile", "matrimonial site", "nri settled abroad",
            "london mein settle hoon", "dubai job", "send gift", "customs for gift", "gold send kiya",
            "jewellery bhej raha hoon", "gift mein diamonds", "order ka refund", "amazon refund process",
            "flipkart refund", "refund ke liye otp", "refund agent", "customer care refund call",
            "order cancel refund paisa aayega", "refund process karne ke liye", "refund form bhariye",
            "upi pin daaliye refund", "card details for quick refund", "facebook account hack", "instagram hacked",
            "someone using your photos", "fake account banaya", "aapki profile se fraud", "aapke naam se message",
            "naye number se call kar raha", "purana dost", "naya number hai mera", "mera phone kho gaya",
            "ye mera new number hai", "pf withdrawal", "epf claim", "pf paisa", "provident fund",
            "pf processing fee", "pf release karne ke liye", "pf account me paisa", "pf claim fas gaya",
            "processing charge pay karein tabhi paisa", "uncle\\'s friend", "severe accident", "icu",
            "transfer 50,000 to this hospital", "don\\'t tell your parents", "there is no time", "police ne mujhe pakad liya",
            "constable paise maang raha", "gpay kar do", "kisi ko mat batana", "accident case mein", "fir likh dega",
            "please 20,000", "please 40,000", "please 50,000", "hospital account urgently", "in the icu",
            "trojan virus on your computer", "install anydesk immediately", "hard drive crashes",
            "microsoft windows support", "windows support team", "detected a trojan", "teamviewer quicksupport install",
            "9 digit code", "engineer can fix it", "your pc is infected", "your system is compromised",
            "kbc mumbai se bol raha hoon", "25 lakh ka lottery", "file charge 12,500", "prize lene ke liye",
            "lucky draw winner", "mahindra thar", "lucky winner", "pay 5000 rupees registration fee",
            "claim your car", "whatsapp lottery", "supreme court clearance certificate", "50,000 rbi safe account",
            "hawala transaction hua hai", "police department se call", "statement record nahi hota digital arrest",
            "money laundering ka warrant", "skype on karo", "cbi officer bol raha hoon", "exclusive stock market insider",
            "vip whatsapp group ko join karo", "200% guaranteed return", "1 hafte mein", "demat account ka id password do",
            "trade laga dunga", "cloud mining platform", "transfer 500 usdt", "earn daily passive income", "no risk",
            "pradhan mantri yojana ke tehat", "1 lakh ka loan bina interest", "file charge 1500 rupees", "kisan samman nidhi",
            "aadhaar number aur bank ka otp", "pre-paid task complete", "10,000 rupees invest karein", "30% profit ke sath",
            "13,000 wapas milenge", "telegram task group", "like youtube videos and subscribe", "earn 5000 rupees daily",
            "pay 1000 rupees security deposit", "work from home part time", "security deposit to start",
            "aadhaar aur pan card mere paas hai", "usko block kar dunga", "relatives ko call karke bataunga",
            "tu defaulter hai", "insurance policy lapse", "premium pending hai", "policy cancel ho jayegi",
            "bonus amount claim", "policy revive karne ke liye", "insurance ka paisa", "health insurance scheme",
            "pm health scheme fee", "ayushman bharat fee", "lic policy ka bonus mature", "85,000 rupaye release karne ke liye",
            "gst aur service charge pay karna hoga", "seedha account mein aa jayega", "policy renew nahi hui isliye",
            "penalty lag gaya hai", "card number daal dijiye", "additional rider available",
            "policy number aur otp jo abhi sms pe aaya", "mediclaim claim", "claim approve ho gaya hai",
            "documentation fee", "release karne ke liye", "20 saal pehle li hui lic policy mature",
            "2.4 lakh milenge", "tax clearance certificate fee", "collect karne ke liye pehle",
            "free cancer screening", "camp aapke area mein aayega", "registration ke liye 300 rupaye advance",
            "camp mein adjust ho jayega", "free health checkup", "doctor aapke ghar aayenge",
            "100 rupaye ka nominal charge", "free dialysis scheme", "slot book karne ke liye pehle",
            "baad mein refund ho jayega", "pm jan arogya yojana", "free 5 lakh ka health insurance",
            "aadhaar pan aur ek otp chahiye", "free cancer detection camp", "100 rupee voluntary donation",
            "enrollment requires your aadhaar", "doctor based in london", "sent a very expensive gift",
            "gold jewelry", "customs in delhi has stopped it", "35,000 rupees duty tax to receive",
            "stuck at mumbai airport immigration", "bond money of 50,000 rupees", "won\\'t let me leave",
            "customs duty tax", "parcel stopped at customs", "purana dost", "facebook hack ho gaya tha",
            "naye number se call kar raha hoon", "emergency hai", "8000 rupaye is upi pe bhej do",
            "kal wapas kar", "instagram influencer", "exclusive group join karne ke liye",
            "999 rupaye subscription", "ratan tata\\'s office", "philanthropy challenge", "send 5000 rupees",
            "mr. tata will donate", "dm your upi", "salman khan ki team", "birthday ke liye selected",
            "private party ka invite", "1500 registration fee", "main arpit hoon", "priya di ka beta",
            "kisi ko mat batana please", "25,000 bhej do is number pe", "token advance 50,000 rupaye",
            "kal rate badh jayega", "koi aur le jayega", "immediately bhejiye", "plot hai noida mein",
            "30,000 advance bhej do", "documents baad mein milenge", "jab wo aayenge", "agreement renew karna hai",
            "ek mahine ka rent advance", "landlord baad mein receipt denge", "owner military mein hain overseas",
            "security advance", "keys courier se aayengi", "token dena hoga online", "owner bahar hain",
            "property verified hai booking platform", "loan ka paisa kab dega", "tera aadhaar aur pan card mere paas",
            "loan ka paisa", "defaulter hai", "relatives ko call", "aapne jo 3000 ka loan liya tha",
            "cashbean app", "penalty ke saath ab 18,000", "agar aaj nahi diya", "10 minutes to pay",
            "upload your compromising", "tag your workplace", "compromising pictures", "pictures to youtube",
            "pay me or i will", "private photos", "personal pictures", "send money or", "account has been limited",
            "account limited due to suspicious", "to restore your account", "pay rs", "to restore",
            "account limited", "paypal india", "account verification fee", "trai ke naye rule",
            "document verify nahi kiya", "aaj raat band", "10 baje band kar diya jayega", "naya rule aya hai",
            "new kyc rule", "accident...hospital...paisa", "papa...accident", "mummy...hospital",
            "kidnapping attempt", "police ki help chahiye", "rs 50,000 chahiye", "dost ka friend",
            "police station mein hoon", "bail ke liye paisa", "not been updated in our new server",
            "power supply will be disconnected", "electricity bill has not been updated", "new server update",
            "call this number immediately", "abhi call karein", "fixed deposit scheme", "12% annual interest guaranteed",
            "rbi registered nbfc", "minimum investment rs 5 lakh", "guaranteed interest", "nidhi company",
            "google maps is paying", "writing reviews", "earn rs 500 per review", "pay rs 3,000 for registration",
            "review writing job", "epfo claim", "technical error ki wajah se reject", "admin charge",
            "re-process karne ke liye", "1800 rupaye", "epf re-process", "dubai mein job karta hoon",
            "uk mein settled", "us mein hoon", "first time india visit", "want to meet you", "rishta pakka",
            "shaadi ke baad settle", "visa ke liye paisa", "marriage visa fee", "advance deposit for flat",
            "token money", "flat book karne ke liye", "plot advance payment", "booking amount",
            "advance karein property", "facebook hack ho gaya", "naye number se", "purane dost ki taraf se",
            "account recover karne ke liye otp", "verify karo account ke liye", "upi lite auto-top-up",
            "feature enable karne ke liye otp", "share karein feature ek baar", "auto-debit enable",
            "3 din mein clear karwa sakta", "former employee hoon", "secret bonus", "galti dhund raha tha ca hoon",
            "undeclared gold", "igi airport customs", "singapore se aaya parcel", "address verify nahi hua",
            "redelivery charge", "dtcd parcel return", "bluedart parcel customs fee", "narcotics case mein",
            "human trafficking ring", "shell company registered", "digital custody", "record mismatch hai",
            "correction fee", "post booster job", "background check fee", "training material fee",
            "bypass surgery schedule", "blood chahiye", "jail mein hoon", "bail maang raha hai",
            "borrowed phone", "unclaimed money", "relief fund", "stamp duty advance", "verification code aayega",
            "misused ho raha hai", "endowment policy", "revival charge", "maturity amount", "forex arbitrage",
            "mutual fund", "hedge fund", "premium group", "linked to updated pan", "flagged by our system for misuse",
            "photo aur details", "contact list mere paas hai", "qatar", "bond", "nri hoon toronto",
            "spin-the-wheel", "loyalty draw", "jaipur highway", "urgently sell", "referral scheme",
            "double karke wapas", "consequences", "intimate photos", "permanently delete", "beta tester grant",
            "official fan club", "notice has been issued", "itr nahi bhara", "broadband router has been hacked",
            "unauthorized purchases", "apple id", "dns settings", "malware detected", "device shield pro",
            "fraud prevention se hain", "qr code", "upgrading your wallet", "phishing attack",
            "refund initiation code", "drug distribution", "investigates transactions linked to your pan",
            "dark web se linked", "nani ka operation", "school teacher ka beta", "hospital admit kiya hai",
            "fractional investment", "luggage was stolen", "anniversary offer", "khud decide karo",
            "simple choice", "audit ke liye freeze", "senior citizens", "account darkweb pe sell",
            "security alert on your phone",
'''

regional_expansion = '''
            # EXTENDED REGIONAL LANGUAGES KEYWORDS (100+ PER LANGUAGE TO MATCH PARITY)
            
            # Tamil Extended
            "உடன் பணம்", "பாதுகாப்பு கணக்கு", "வங்கி கணக்கு", "உடனடி பணம்", "போலீஸ்", "ஏடிஎம் கார்டு", 
            "லாட்டரி", "பெற்றீர்", "செலுங்கள்", "மருத்துவார்", "அனுப்பு", "கார்டு தடுக்கப்படும்", "பூர்த்தி செய்யுங்கள்", 
            "ஆதார்", "பங்கு", "ஓடிபி", "வங்கி கணக்கு முடக்கப்பட்டுள்ளது", "கேஒய்சி", "முதலீடு", "வீட்டிலிருந்தே வேலை", 
            "பங்குச் சந்தை", "சுங்க வரி", "பார்சல்", "மின்சாரம் துண்டிக்கப்படும்", "மின் கட்டணம்", "மருத்துவமனையில்", 
            "விபத்து", "அவசரம்", "கைது", "சிபிஐ", "வழக்கு", "கிரிப்டோ", "பணம் அனுப்புங்கள்", "பரிசு",
            "டிஜிட்டல் கைது", "சுங்க அதிகாரிகள்", "பார்சல் தடுத்து நிறுத்தப்பட்டுள்ளது", "சட்டவிரோத பொருட்கள்", 
            "மின் கட்டணம் புதுப்பிக்கப்படவில்லை", "இன்றிரவு மின்சாரம் துண்டிக்கப்படும்", "பங்குச்சந்தை முதலீடு",
            "பகுதி நேர வேலை", "கூகுள் மேப்ஸ் மதிப்புரை", "முன்பணம்", "ஒடிபி பகிரவும்", "கணக்கு முடக்கம்", "அவசர மருத்துவ உதவி",
            "காவல்துறை அதிகாரி", "கைது வாரண்ட்", "பணம் மாற்று", "உடனடியாக பணம் அனுப்பு", "வீடியோ கால்", "சட்டவிரோத பரிவர்த்தனை",
            "கணக்கு முடக்கப்படும்", "பரிசு வென்றுள்ளீர்கள்", "கடன் ஆப்", "தனிப்பட்ட வீடியோ", "வீடியோ லீக்", "கடன் திருப்பிச் செலுத்து",
            "தொலைபேசி தொலைந்துவிட்டது", "நண்பரின் எண்", "மருத்துவமனையில் அனுமதிக்கப்பட்டுள்ளார்", "50000 தேவை", "அவசர அறுவை சிகிச்சை",
            "வாட்ஸ்அப் கணக்கு", "வரி ஏய்ப்பு", "நீதிமன்றம்", "காவல் நிலையம்", "பிணை", "நம்பகமான நண்பர்", "மிரட்டல்", "போலீஸ் வழக்கு",
            "ஆதார் கார்டு அனுப்பு", "பாஸ்வேர்ட்", "நெட் பேங்கிங்", "பணம் திருப்பி தரப்படும்", "கேஒய்சி புதுப்பிக்கவும்",
            "பார்சல் திரும்பி போகும்", "சிபிஐ ஆபிசர்", "உடனடி கைது", "கோர்ட் ஆர்டர்", "உடனடி கட்டணம்", "நண்பர் விபத்து",
            
            # Telugu Extended
            "డబ్బ్ల్యూ మనీ", "బ్యాంక్ ఖాతా", "తక్షణ మనీ", "వెంటనే పంపించండి", "పాసవర్డ్", "ఒటిపి", "వర్క్ ఫ్రమ్ హోమ్", 
            "నెలగు", "సంపాదిందు", "రిజిస్ట్రేషన్ ఫీ", "చెల్లవండి", "పెట్టింగ్ స్కీమ్", "పెట్టిండి", "పొందుతారు", 
            "గ్యారంటీ ఆమోదింగం", "ఇన్షురెన్స్ పాలిసీ", "రద్దు", "అరెస్ట్", "పోలీస్", "కేసు", "బ్యాంక్ ఖాతా బ్లాక్", 
            "కేవైసీ", "పిన్", "పెట్టుబడి", "స్టాక్ మార్కెట్", "కస్టమ్స్", "పార్సెల్", "కరెంట్ కట్", "విద్యుత్ బిల్లు", 
            "ఆసుపత్రిలో", "ప్రమాదం", "అత్యవసరం", "ఆధార్", "ఓటీపీ పంచుకోవద్దు", "లాటరీ", "గెలుచుకున్నారు",
            "డిజిటల్ అరెస్ట్", "కస్టమ్స్ అధికారులు", "పార్సెల్ బ్లాక్ చేయబడింది", "చట్టవిరుద్ధమైన వస్తువులు",
            "విద్యుత్ బిల్లు అప్‌డేట్ కాలేదు", "ఈ రాత్రి కరెంట్ కట్", "స్టాక్ మార్కెట్ పెట్టుబడి", "పార్ట్ టైమ్ జాబ్",
            "గూగుల్ మ్యాప్స్ రివ్యూ", "అడ్వాన్స్", "ఓటీపీ చెప్పండి", "ఖాతా ఫ్రీజ్", "అత్యవసర వైద్య సహాయం",
            "పోలీస్ ఆఫీసర్", "అరెస్ట్ వారెంట్", "డబ్బు బదిలీ చేయండి", "వెంటనే డబ్బు పంపండి", "వీడియో కాల్", "చట్టవిరుద్ధమైన లావాదేవీ",
            "ఖాతా బ్లాక్ చేయబడుతుంది", "బహుమతి గెలుచుకున్నారు", "లోన్ యాప్", "వ్యక్తిగత వీడియో", "వీడియో லీక్", "లోన్ తిరిగి చెల్లించండి",
            "ఫోన్ పోయింది", "స్నేహితుడి నంబర్", "ఆసుపత్రిలో చేరారు", "50000 కావాలి", "అత్యవసర సర్జరీ",
            "వాట్సాప్ ఖాతా", "పన్ను ఎగవేత", "కోర్టు", "పోలీస్ స్టేషన్", "బెయిల్", "నమ్మకమైన స్నేహితుడు", "బెదిరింపు", "పోలీస్ కేసు",
            "ఆధార్ పంపండి", "సీబీఐ ఆఫీసర్", "పార్సెల్ తిరిగి పంపబడుతుంది", "కస్టమ్స్ డ్యూటీ కట్టాలి", "అకౌంట్ బ్లాక్ అవుతుంది",
            "ఏటీఎం కార్డ్ బ్లాక్", "కోర్టు ఆర్డర్ వచ్చింది", "అకౌంట్ ఫ్రీజ్ చేశారు", "లోన్ కట్టాలి", "యూట్యూబ్ లైక్ చేయండి",
            
            # Bengali Extended
            "টাকা পাঠাও", "ব্যাংক অ্যাকাউন্ট", "অবিলম্ব", "পাসওয়ার্ড", "এটিএম কার্ড", "ওটিপি", "লটারি", "জিতেছেন", 
            "পুরস্কার", "প্রসেসিং ফি", "হোম ফ্রম জব", "মাসিক", "আয", "রেজিস্ট্রেশন ফি", "হাসপাতালে", "তাৎরিত", 
            "গ্রেফতার", "পুলিশ", "মামলা", "অ্যাকাউন্ট ব্লক", "কেওয়াইসি", "পিন", "বিনিয়োগ", "ওয়ার্ক ফ্রম হোম", 
            "শেয়ার বাজার", "কাস্টমস", "পার্সেল", "বিদ্যুৎ বিচ্ছিন্ন", "দুর্ঘটনা", "জরুরি", "আধার কার্ড", "সিবিআই",
            "ডিজিটাল গ্রেফতার", "কাস্টমস অফিসার", "পার্সেল আটক করা হয়েছে", "বেআইনি জিনিস", "বিদ্যুৎ বিল আপডেট হয়নি",
            "আজ রাতে বিদ্যুৎ বিচ্ছিন্ন", "শেয়ার বাজারে বিনিয়োগ", "পার্ট টাইম চাকরি", "গুগল ম্যাপস রিভিউ", 
            "অগ্রিম পেমেন্ট", "ওটিপি শেয়ার করুন", "অ্যাকাউন্ট ফ্রিজ", "জরুরী চিকিৎসা",
            "পুলিশ অফিসার", "গ্রেফতারি পরোয়ানা", "টাকা স্থানান্তর করুন", "অবিলম্বে টাকা পাঠান", "ভিডিও কল", "বেআইনি লেনদেন",
            "অ্যাকাউন্ট ব্লক করা হবে", "পুরস্কার জিতেছেন", "লোন অ্যাপ", "ব্যক্তিগত ভিডিও", "ভিডিও ফাঁস", "লোন পরিশোধ করুন",
            "ফোন হারিয়ে গেছে", "বন্ধুর নম্বর", "হাসপাতালে ভর্তি", "50000 চাই", "জরুরী সার্জারি",
            "হোয়াটসঅ্যাপ অ্যাকাউন্ট", "কর ফাঁকি", "আদালত", "থানা", "জামিন", "বিশ্বস্ত বন্ধু", "হুমকি", "পুলিশ কেস",
            "আধার কার্ড পাঠান", "পার্সেল কাস্টমসে আটকে আছে", "ফাইন দিতে হবে", "ব্যাংক অ্যাকাউন্ট বন্ধ হয়ে যাবে",
            "এটিএম কার্ড বন্ধ", "শেয়ার বাজার লভ্যাংশ", "ইউটিউব লাইক করুন", "লোন বাকি আছে", "ভিডিও ফাঁস করে দেব",
            
            # Marathi Extended
            "पैसे पाठवा", "बँक खाते", "तात्काळ", "पासवर्ड", "एटीएम कार्ड", "ओटीपी", "गुंतवनिकी स्कीम", "गुंतव", 
            "मिळो", "सरकारारी योजना", "लॉटरी", "जिंकले", "प्रोसेसिंग फी", "घरू फ्रम जॉब", "महिने", "कमावा", 
            "नोंदणी फी", "अटक", "पोलिस", "गुन्हा", "खाते ब्लॉक", "केवायसी", "पिन", "गुंतवणूक", "वर्क फ्रॉम होम", 
            "शेअर बाजार", "कस्टम्स", "पार्सल", "वीज खंडित", "वीज बिल", "रुग्णालयात", "अपघात", "तातडीने", "डिजिटल अरेस्ट",
            "कस्टम अधिकारी", "पार्सल अडवले आहे", "बेकायदेशीर वस्तू", "वीज बिल अपडेट केलेले नाही", "आज रात्री वीज खंडित",
            "शेअर बाजारात गुंतवणूक", "पार्ट टाइम जॉब", "गुगल मॅप्स रिव्ह्यू", "अॅडव्हान्स पेमेंट", "ओटीपी सांगा",
            "खाते गोठवले", "तातडीची वैद्यकीय मदत",
            "पोलिस अधिकारी", "अटक वॉरंट", "पैसे ट्रान्सफर करा", "लगेच पैसे पाठवा", "व्हिडिओ कॉल", "बेकायदेशीर व्यवहार",
            "खाते ब्लॉक केले जाईल", "बक्षीस जिंकले", "लोन ॲप", "खाजगी व्हिडिओ", "व्हिडिओ लीक", "लोन परत करा",
            "फोन हरवला", "मित्राचा नंबर", "रुग्णालयात दाखल", "50000 पाहिजे", "तातडीची शस्त्रक्रिया",
            "व्हॉट्सॲप खाते", "कर चोरी", "न्यायालय", "पोलिस स्टेशन", "जामीन", "विश्वासू मित्र", "धमकी", "पोलिस केस",
            "आधार कार्ड पाठवा", "पार्सल अडकले आहे", "कस्टम ड्युटी भरा", "खाते बंद होईल", "एटीएम कार्ड ब्लॉक", 
            "सीआयडी ऑफिसर", "इन्कम टॅक्स", "लोन बाकी आहे", "व्हिडिओ व्हायरल करेन", "युट्यूब लाईक करा",
            
            # Kannada Extended
            "ಹಣ ಕಳುಹಿಸಿ", "ಬ್ಯಾಂಕ್ ಖಾತೆ", "ತಕ್ಷಣ", "ಪಾಸ್‌ವರ್ಡ್", "ಏಟಿಎಂ ಕಾರ್ಡ್", "ಓಟಿಪಿ", "ಇನ್ಶುರೆನ್ಸ್ ಪಾಲಿಸಿ", 
            "ರದ್ದು", "ಚೆಲ್ಲವಂಡಿ", "ಹೋಮ್ ಫ್ರಮ್ ಜಾಬ್", "ತಿಂಗಳಿಂದಿರು", "ಸಂಪಾದಿಸು", "ನೋಂದಣಿ ಫೀ", "ಲಾಟರಿ", "ಗೆದ್ದುವು", 
            "ಪ್ರಾಸೆಸಿಂಗ್ ಫೀ", "ಬಂಧನ", "ಪೊಲೀಸ್", "ಪ್ರಕರಣ", "ಖಾತೆ ನಿರ್ಬಂಧಿಸಲಾಗಿದೆ", "ಕೆವೈಸಿ", "ಪಿನ್", "ಹೂಡಿಕೆ", 
            "ವರ್ಕ್ ಫ್ರಮ್ ಹೋಮ್", "ವಿದ್ಯುತ್ ಕಡಿತ", "ಆಸ್ಪತ್ರೆಯಲ್ಲಿ", "ಅಪಘಾತ", "ತುರ್ತು", "ಆಧಾರ್", "ಪಾರ್ಸೆಲ್",
            "ಡಿಜಿಟಲ್ ಬಂಧನ", "ಕಸ್ಟಮ್ಸ್ ಅಧಿಕಾರಿ", "ಪಾರ್ಸೆಲ್ ತಡೆಹಿಡಿಯಲಾಗಿದೆ", "ಕಾನೂನುಬಾಹಿರ ವಸ್ತುಗಳು",
            "ವಿದ್ಯುತ್ ಬಿಲ್ ನವೀಕರಿಸಿಲ್ಲ", "ಇಂದು ರಾತ್ರಿ ವಿದ್ಯುತ್ ಕಡಿತ", "ಷೇರು ಮಾರುಕಟ್ಟೆ ಹೂಡಿಕೆ", "ಅರೆಕಾಲಿಕ ಕೆಲಸ",
            "ಗೂಗಲ್ ಮ್ಯಾಪ್ಸ್ ವಿಮರ್ಶೆ", "ಮುಂಗಡ ಪಾವತಿ", "ಓಟಿಪಿ ಹಂಚಿಕೊಳ್ಳಿ", "ಖಾತೆ ಫ್ರೀಜ್", "ತುರ್ತು ವೈದ್ಯಕೀಯ ನೆರವು",
            "ಪೊಲೀಸ್ ಅಧಿಕಾರಿ", "ಬಂಧನ ವಾರಂಟ್", "ಹಣ ವರ್ಗಾಯಿಸಿ", "ತಕ್ಷಣ ಹಣ ಕಳುಹಿಸಿ", "ವೀಡಿಯೊ ಕರೆ", "ಅಕ್ರಮ ವಹಿವಾಟು",
            "ಖಾತೆ ನಿರ್ಬಂಧಿಸಲಾಗುತ್ತದೆ", "ಬಹುಮಾನ ಗೆದ್ದಿದ್ದೀರಿ", "ಲೋನ್ ಆಪ್", "ಖಾಸಗಿ ವೀಡಿಯೊ", "ವೀಡಿಯೊ ಲೀಕ್", "ಲೋನ್ ಮರುಪಾವತಿಸಿ",
            "ಫೋನ್ ಕಳೆದುಹೋಗಿದೆ", "ಸ್ನೇಹಿತನ ಸಂಖ್ಯೆ", "ಆಸ್ಪತ್ರೆಗೆ ದಾಖಲಾಗಿದ್ದಾರೆ", "50000 ಬೇಕು", "ತುರ್ತು ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ",
            "ವಾಟ್ಸಾಪ್ ಖಾತೆ", "ತೆರಿಗೆ ವಂಚನೆ", "ನ್ಯಾಯಾಲಯ", "ಪೊಲೀಸ್ ಠಾಣೆ", "ಜಾಮೀನು", "ವಿಶ್ವಾಸಾರ್ಹ ಸ್ನೇಹಿತ", "ಬೆದರಿಕೆ", "ಪೊಲೀಸ್ ಪ್ರಕರಣ",
            "ಆಧಾರ್ ಕಳುಹಿಸಿ", "ಕಸ್ಟಮ್ಸ್ ತೆರಿಗೆ", "ಖಾತೆ ಮುಚ್ಚಲಾಗುತ್ತದೆ", "ಏಟಿಎಂ ಕಾರ್ಡ್ ಬ್ಲಾಕ್", "ಸಿಬಿಐ ಅಧಿಕಾರಿ",
            "ಲೋನ್ ಕಟ್ಟಬೇಕು", "ವೀಡಿಯೊ ವೈರಲ್ ಮಾಡುತ್ತೇನೆ", "ಯೂಟ್ಯೂಬ್ ಲೈಕ್ ಮಾಡಿ", "ಕೋಲಾಟರಲ್ ಫೀ", "ರಿಫಂಡ್ ಹಣ",
            
            # Malayalam Extended
            "പണം അയച്ചു", "ബാങ്ക് അക്കൗണ്ട്", "ഉടൻ", "പാസ്‌വേഡ്", "എടിഎം കാർഡ്", "ഒടിപി", "ആശുപത്രിയിൽ", "പെട്ടി", 
            "ആവശ്യം", "ഇപ്പോ", "അയച്ചു", "നിക്ഷം സ്കീം", "നിക്ഷി", "ലഭിക്കും", "സർക്കാരി പദ്ധതി", "ലോട്ടറി", 
            "ജിക്കുക", "പ്രോസസിംഗ് ഫീ", "അറസ്റ്റ്", "പോലീസ്", "കേസ്", "അക്കൗണ്ട് ബ്ലോക്ക്", "കെവൈസി", "നിക്ഷേപം", 
            "വർക്ക് ഫ്രം ഹോം", "വൈദ്യുതി വിച്ഛേദിക്കും", "അപകടം", "അടിയന്തരം", "ആധാർ", "പാഴ്സൽ കസ്റ്റംസ്",
            "ഡിജിറ്റൽ അറസ്റ്റ്", "കസ്റ്റംസ് ഓഫീസർ", "പാഴ്സൽ തടഞ്ഞുവെച്ചിരിക്കുന്നു", "നിയമവിരുദ്ധ സാധനങ്ങൾ",
            "വൈദ്യുതി ബിൽ അപ്ഡേറ്റ് ചെയ്തിട്ടില്ല", "ഇന്ന് രാത്രി വൈദ്യുതി വിച്ഛേദിക്കും", "ഓഹരി വിപണി നിക്ഷേപം", "പാർട്ട് ടൈം ജോലി",
            "ഗൂഗിൾ മാപ്സ് റിവ്യൂ", "മുൻകൂർ പേയ്‌മെന്റ്", "ഒടിപി പങ്കിടുക", "അക്കൗണ്ട് ഫ്രീസ്", "അടിയന്തര വൈദ്യസഹായം",
            "പോലീസ് ഓഫീസർ", "അറസ്റ്റ് വാറണ്ട്", "പണം കൈമാറുക", "ഉടൻ പണം അയക്കുക", "വീഡിയോ കോൾ", "നിയമവിരുദ്ധ ഇടപാട്",
            "അക്കൗണ്ട് ബ്ലോക്ക് ചെയ്യും", "സമ്മാനം നേടിയിരിക്കുന്നു", "ലോൺ ആപ്പ്", "സ്വകാര്യ വീഡിയോ", "വീഡിയോ ചോർന്നു", "ലോൺ തിരിച്ചടയ്ക്കുക",
            "ഫോൺ നഷ്ടപ്പെട്ടു", "സുഹൃത്തിന്റെ നമ്പർ", "ആശുപത്രിയിൽ പ്രവേശിപ്പിച്ചു", "50000 വേണം", "അടിയന്തര സർജറി",
            "വാട്ട്‌സ്ആപ്പ് അക്കൗണ്ട്", "നികുതി വെട്ടിപ്പ്", "കോടതി", "പോലീസ് സ്റ്റേഷൻ", "ജാമ്യം", "വിശ്വസ്ത സുഹൃത്ത്", "ഭീഷണി", "പോലീസ് കേസ്",
            "ആധാർ അയക്കുക", "കസ്റ്റംസ് തീരുവ", "അക്കൗണ്ട് മരവിപ്പിച്ചു", "എടിഎം കാർഡ് ബ്ലോക്ക്", "സിബിഐ ഓഫീസർ",
            "ലോൺ അടയ്ക്കണം", "വീഡിയോ വൈറലാക്കും", "യൂട്യൂബ് ലൈക്ക് ചെയ്യുക", "റീഫണ്ട് തുക", "അടിയന്തര ഫീസ്",
            
            # Gujarati Extended
            "પૈસા મોકલો", "બેંક એકાઉન્ટ", "તાત્કાલિક", "પાસવર્ડ", "એટીએમ કાર્ડ", "ઓટીપી", "રોકાણ યોજના", 
            "ઇન્વેસ્ટ કરો", "મળશે", "સરકારી યોજના", "લોટરી", "જીત્યા", "પ્રોસેસિંગ ફી", "વર્ક ફ્રોમ હોમ", 
            "મહિના", "કમાઓ", "રજીસ્ટ્રેશન ફી", "ધરપકડ", "પોલીસ", "કેસ", "એકાઉન્ટ બ્લોક", "કેવાયસી", 
            "પીન", "રોકાણ", "શેરબજાર", "કસ્ટમ્સ", "પાર્સલ", "વીજળી કપાશે", "વીજળી બિલ", "હોસ્પિટલમાં", 
            "અકસ્માત", "ઇમરજન્સી", "આધાર",
            "ડિજિટલ ધરપકડ", "કસ્ટમ્સ અધિકારી", "પાર્સલ પકડાયું છે", "ગેરકાયદેસર વસ્તુઓ",
            "વીજળી બિલ અપડેટ થયું નથી", "આજે રાત્રે વીજળી કપાશે", "શેરબજારમાં રોકાણ", "પાર્ટ ટાઇમ નોકરી",
            "ગૂગલ મેપ્સ રિવ્યુ", "એડવાન્સ પેમેન્ટ", "ઓટીપી શેર કરો", "એકાઉન્ટ ફ્રીઝ", "ઇમરજન્સી મેડિકલ સહાય",
            "પોલીસ અધિકારી", "ધરપકડ વોરંટ", "પૈસા ટ્રાન્સફર કરો", "તાત્કાલિક પૈસા મોકલો", "વિડીયો કોલ", "ગેરકાયદેસર વ્યવહાર",
            "એકાઉન્ટ બ્લોક થશે", "ઇનામ જીત્યા છો", "લોન એપ", "ખાનગી વિડીયો", "વિડીયો લીક", "લોન ચૂકવો",
            "ફોન ખોવાઈ ગયો", "મિત્રનો નંબર", "હોસ્પિટલમાં દાખલ", "50000 જોઈએ", "ઇમરજન્સી સર્જરી",
            "વોટ્સએપ એકાઉન્ટ", "ટેક્સ ચોરી", "કોર્ટ", "પોલીસ સ્ટેશન", "જામીન", "વિશ્વાસુ મિત્ર", "ધમકી", "પોલીસ કેસ",
            "આધાર કાર્ડ મોકલો", "કસ્ટમ ડ્યુટી ભરો", "ખાતું બંધ થશે", "એટીએમ કાર્ડ બ્લોક", "સીબીઆઈ ઓફિસર",
            "લોન બાકી છે", "વિડીયો વાયરલ કરીશ", "યુટ્યુબ લાઈક કરો", "રિફંડ મળશે", "પેનલ્ટી આપવી પડશે",
            
            # Punjabi Extended
            "ਪੈਸੇ ਭੇਜੋ", "ਬੈਂਕ ਖਾਤਾ", "ਤੁਰੰਤ", "ਪਾਸਵਰਡ", "ਏਟੀਐਮ ਕਾਰਡ", "ਓਟੀਪੀ", "ਨਿਵੇਸ਼ ਸਕੀਮ", "ਨਿਵੇਸ਼ ਕਰੋ", 
            "ਮਿਲੇਗਾ", "ਸਰਕਾਰੀ ਸਕੀਮ", "ਲਾਟਰੀ", "ਜਿੱਤੀ", "ਪ੍ਰੋਸੈਸਿੰਗ ਫੀਸ", "ਵਰਕ ਫਰੋਮ ਹੋਮ", "ਮਹੀਨਾ", "ਕਮਾਓ", 
            "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਫੀਸ", "ਗ੍ਰਿਫਤਾਰੀ", "ਪੁਲਿਸ", "ਕੇਸ", "ਖਾਤਾ ਬਲਾਕ", "ਕੇਵਾਈਸੀ", "ਪਿਨ", "ਨਿਵੇਸ਼", 
            "ਸ਼ੇਅਰ ਬਾਜ਼ਾਰ", "ਕਸਟਮ", "ਪਾਰਸਲ", "ਬਿਜਲੀ ਕੱਟੀ ਜਾਵੇਗੀ", "ਬਿਜਲੀ ਬਿੱਲ", "ਹਸਪਤਾਲ ਵਿੱਚ", "ਹਾਦਸਾ", 
            "ਐਮਰਜੈਂਸੀ", "ਆਧਾਰ",
            "ਡਿਜੀਟਲ ਗ੍ਰਿਫਤਾਰੀ", "ਕਸਟਮ ਅਫਸਰ", "ਪਾਰਸਲ ਫੜਿਆ ਗਿਆ ਹੈ", "ਗੈਰ-ਕਾਨੂੰਨੀ ਚੀਜ਼ਾਂ",
            "ਬਿਜਲੀ ਬਿੱਲ ਅਪਡੇਟ ਨਹੀਂ ਹੋਇਆ", "ਅੱਜ ਰਾਤ ਬਿਜਲੀ ਕੱਟੀ ਜਾਵੇਗੀ", "ਸ਼ੇਅਰ ਬਾਜ਼ਾਰ ਨਿਵੇਸ਼", "ਪਾਰਟ ਟਾਈਮ ਨੌਕਰੀ",
            "ਗੂਗਲ ਮੈਪਸ ਰਿਵਿਊ", "ਐਡਵਾਂਸ ਪੇਮੈਂਟ", "ਓਟੀਪੀ ਸ਼ੇਅਰ ਕਰੋ", "ਖਾਤਾ ਫ੍ਰੀਜ਼", "ਐਮਰਜੈਂਸੀ ਮੈਡੀਕਲ ਮਦਦ",
            "ਪੁਲਿਸ ਅਫਸਰ", "ਗ੍ਰਿਫਤਾਰੀ ਵਾਰੰਟ", "ਪੈਸੇ ਟਰਾਂਸਫਰ ਕਰੋ", "ਤੁਰੰਤ ਪੈਸੇ ਭੇਜੋ", "ਵੀਡੀਓ ਕਾਲ", "ਗੈਰ-ਕਾਨੂੰਨੀ ਲੈਣ-ਦੇਣ",
            "ਖਾਤਾ ਬਲਾਕ ਹੋ ਜਾਵੇਗਾ", "ਇਨਾਮ ਜਿੱਤਿਆ ਹੈ", "ਲੋਨ ਐਪ", "ਪ੍ਰਾਈਵੇਟ ਵੀਡੀਓ", "ਵੀਡੀਓ ਲੀਕ", "ਲੋਨ ਵਾਪਸ ਕਰੋ",
            "ਫੋਨ ਗੁੰਮ ਹੋ ਗਿਆ", "ਦੋਸਤ ਦਾ ਨੰਬਰ", "ਹਸਪਤਾਲ ਦਾਖਲ", "50000 ਚਾਹੀਦੇ ਹਨ", "ਐਮਰਜੈਂਸੀ ਸਰਜਰੀ",
            "ਵਟਸਐਪ ਖਾਤਾ", "ਟੈਕਸ ਚੋਰੀ", "ਕੋਰਟ", "ਪੁਲਿਸ ਸਟੇਸ਼ਨ", "ਜ਼ਮਾਨਤ", "ਭਰੋਸੇਮੰਦ ਦੋਸਤ", "ਧਮਕੀ", "ਪੁਲਿਸ ਕੇਸ",
            "ਆਧਾਰ ਕਾਰਡ ਭੇਜੋ", "ਕਸਟਮ ਡਿਊਟੀ ਭਰੋ", "ਖਾਤਾ ਬੰਦ ਹੋਵੇਗਾ", "ਏਟੀਐਮ ਕਾਰਡ ਬਲਾਕ", "ਸੀਬੀਆਈ ਅਫਸਰ",
            "ਲੋਨ ਬਾਕੀ ਹੈ", "ਵੀਡੀਓ ਵਾਇਰਲ ਕਰਾਂਗਾ", "ਯੂਟਿਊਬ ਲਾਈਕ ਕਰੋ", "ਰਿਫੰਡ ਮਿਲੇਗਾ", "ਪੈਨਲਟੀ ਦੇਣੀ ਪਵੇਗੀ",
'''

content = re.sub(r'(# Extreme twisted scam keywords.*?"cyber crime", "anti-scam",)', r'\\1\\n' + hindi_expansion, content, flags=re.DOTALL)
content = re.sub(r'("पोलीस केस",)', r'\\1\\n' + regional_expansion, content, flags=re.DOTALL)

with open('D:/PhaseGuard/apps/api/factcheck/local_llm.py', 'w', encoding='utf-8') as f:
    f.write(content)
print('Done injecting massive keywords')
